version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
